#!/usr/bin/env zsh

########################### Alias ###########################

# 独自function
alias tma='peco-tmux-attach'

########################### Key Bindings ###########################

# 履歴からコマンド選択
zle -N peco-select-history
bindkey '^r' peco-select-history

# ディレクトリ検索
zle -N peco-find-directory
bindkey '^f^f' peco-find-directory

# スニペット検索
zle -N peco-snippets
bindkey '^x^s' peco-snippets
zle -N peco-snippets-copy
bindkey '^x^x' peco-snippets-copy



########################### Function ###########################


# コマンド履歴のpeco検索
function peco-select-history() {
    local tac
    if which tac > /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi
    BUFFER=$(history -n 1 | eval $tac | awk '!a[$0]++' | peco --query "$LBUFFER")
    CURSOR=$#BUFFER
    # zle clear-screen
}

# ディレクトリ検索
# http://qiita.com/ymorired/items/4b0d8e95786efc1378b4
function peco-find-directory() {
    local current_buffer=$BUFFER
    # .git系など不可視フォルダは除外
    local selected_dir="$(fd --type d --max-depth 8 | peco --prompt '📁  >')"
    if [ -d "$selected_dir" ]; then
        BUFFER="${current_buffer} ${selected_dir}"
        CURSOR=$#BUFFER
    fi
    zle clear-screen
}

# tmux セッション検索(alias用)
function peco-tmux-attach() {
    local res=$(tmux list-sessions | peco | awk -F':' '{print $1}')
    if [ -n "$res" ]; then
        tmux attach -t ${res}
    fi
}


# スニペット検索
function peco-snippets() {
    BUFFER=$(grep -v "^#" ~/.snippets | peco --query "$LBUFFER")
    zle clear-screen
}

function peco-snippets-copy() {
    BUFFER=$(grep -v "^#" ~/.snippets | peco --query "$LBUFFER" | pbcopy)
    zle clear-screen
}


# jvc() { export JAVA_HOME=`/usr/libexec/java_home -X | python -c 'import sys, plistlib; plist = plistlib.readPlist(sys.stdin); print "\n".join(str(dict["JVMVersion"]) for dict in plist)' | peco --prompt "Switch Java Version >" | xargs /usr/libexec/java_home -v` }

